@startuml
class User extends UriEntity implements UserDetails {
  username : String
  password : String
  email : String
  dni: String
  dateOfBirth: String
}


class UriEntity {
  uri : String
}
abstract class Pet extends UriEntity {
  id: Long
  name: String
  dateOfBirth: Date
  isAdopted: Boolean
  colour: String
  size: Integer
  chip: String
  sex: String
  race: String
  dangerous: Boolean
}
class Dog extends Pet {
    barkingLevel: Integer
}

class Cat extends Pet {
    meowingLevel: Integer
}

class Shelter extends UriEntity {
  id: Long
  name: String
  email: String
  mobile : String
  createdAt: DateTime
  updatedAt: DateTime
  isActive: Boolean
}

class Location {
 id: Long
 address: String
 latitude: Float
 longitude: Float
 province: String
 city: String
 postalCode: Integer
}

class ShelterCertificate {
  id: Long
  expirationDate: DateTime
}

class Schedule {
    id: Long
    startTime: Time
    endTime: Time
}

class Adoptions {
    dateOfAdoption: DateTime
}

class Role {
    id: Long
    name: String
}

class Permission {
    id: Long
    name: String
}


User "1" --right-- "*" Resource : owner <
Location "1" -> "1" Shelter : has>
Shelter "1" -> "*" User : < pertain
Shelter "1" -> "*" Pet : has >
Shelter "1" -> "1" ShelterCertificate : has >
Schedule "*" -> "1" Shelter :available >

Adoptions "1" -> "1" Pet :adopted >
Adoptions "1" -> "1" User :adopt <

User "*" -> "*" Role
Role "*" -> "*" Permission

@enduml
