allowed-origins: "https://mypets-geiade.netlify.app, https://deploy-preview-*--mypets-geiade.netlify.app"

logging:
    level:
        org:
            hibernate: error
            springframework.core: error
            springframework.web: error
        root: error
